openapi: 3.0.0
info:
  title: StronGuru API Documentation
  version: 1.0.0
  description: Centralized and modular documentation of StronGuru backend APIs.
servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /users:
    $ref: './users.yaml#/paths/~1users'
  /auth/login:
    $ref: './auth.yaml#/paths/~1auth~1login'
  /auth/signup/professional:
    $ref: './auth.yaml#/paths/~1auth~1signup~1professional'
  /auth/refresh-token:
    $ref: './auth.yaml#/paths/~1auth~1refresh-token'
  /auth/logout:
    $ref: './auth.yaml#/paths/~1auth~1logout'
  /token/activate/{token}:
    $ref: './token.yaml#/paths/~1token~1activate~1{token}'
  /professionals:
    $ref: './professionals.yaml#/paths/~1professionals'
  /professionals/professional/{id}:
    $ref: './professionals.yaml#/paths/~1professionals~1professional~1{id}'
  /professionals/professional/{id}/password:
    $ref: './professionals.yaml#/paths/~1professionals~1professional~1{id}~1password'
  /athletes:
    $ref: './athletes.yaml#/paths/~1athletes'
  /devices/user/{userId}:
    $ref: './userDevices.yaml#/paths/~1devices~1user~1{userId}'
  /devices/{id}:
    $ref: './userDevices.yaml#/paths/~1devices~1{id}'

components:
  $ref: './components/schemas.yaml'